// Generated by scripts/generate-showcase-stories.mjs
import '../../../src/showcase/showcase.css';
import type { Meta, StoryObj } from '@storybook/react-vite';
import type { ShowcaseScenarioId } from '../../../src/showcase/index.js';
import {
  mantineShowcaseEntries,
  SingleShowcaseStory,
} from '../../../src/showcase/index.js';

type ComponentStoryProps = {
  scenarioId?: ShowcaseScenarioId;
};

const entry = mantineShowcaseEntries.find(
  (showcaseEntry) => showcaseEntry.id === 'mantine-alert',
);

if (!entry) {
  throw new Error('Missing showcase entry: mantine-alert');
}

function AlertStory({ scenarioId = 'preview' }: ComponentStoryProps) {
  return (
    <SingleShowcaseStory entry={entry} library="mantine" scenarioId={scenarioId} />
  );
}

const meta = {
  title: 'Mantine/Components/Alert',
  component: AlertStory,
  args: {
    scenarioId: 'preview',
  },
  argTypes: {
    scenarioId: {
      control: 'select',
      options: ['preview', 'variants'],
      description:
        'Switch between the default component preview and the variant matrix.',
    },
  },
  parameters: {
    layout: 'fullscreen',
  },
} satisfies Meta<typeof AlertStory>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Preview: Story = {
  args: {
    scenarioId: 'preview',
  },
};

export const Variants: Story = {
  args: {
    scenarioId: 'variants',
  },
};
