// Generated by scripts/generate-showcase-stories.mjs
import '../../../src/showcase/showcase.css';
import type { Meta, StoryObj } from '@storybook/react-vite';
import type { ShowcaseScenarioId } from '../../../src/showcase/index.js';
import {
  mantineShowcaseEntries,
  SingleShowcaseStory,
} from '../../../src/showcase/index.js';

type ComponentStoryProps = {
  scenarioId?: ShowcaseScenarioId;
};

const entry = mantineShowcaseEntries.find(
  (showcaseEntry) => showcaseEntry.id === 'mantine-switch',
);

if (!entry) {
  throw new Error('Missing showcase entry: mantine-switch');
}

function SwitchStory({ scenarioId = 'preview' }: ComponentStoryProps) {
  return (
    <SingleShowcaseStory entry={entry} library="mantine" scenarioId={scenarioId} />
  );
}

const meta = {
  title: 'Mantine/Components/Switch',
  component: SwitchStory,
  args: {
    scenarioId: 'preview',
  },
  argTypes: {
    scenarioId: {
      control: 'select',
      options: [
        'preview',
        'variants',
        'states',
        'composition',
        'tokens',
        'accessibility',
        'playground',
      ],
      description: 'Switch between component documentation scenarios.',
    },
  },
  parameters: {
    layout: 'fullscreen',
  },
} satisfies Meta<typeof SwitchStory>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Preview: Story = {
  args: {
    scenarioId: 'preview',
  },
  parameters: {
    docs: {
      description: {
        story: 'Recommended default usage for the component.',
      },
    },
  },
};

export const Variants: Story = {
  args: {
    scenarioId: 'variants',
  },
  parameters: {
    docs: {
      description: {
        story: 'Supported visual variants and key style axes.',
      },
    },
  },
};

export const States: Story = {
  args: {
    scenarioId: 'states',
  },
  parameters: {
    docs: {
      description: {
        story: 'Interactive and validation states.',
      },
    },
  },
};

export const Composition: Story = {
  args: {
    scenarioId: 'composition',
  },
  parameters: {
    docs: {
      description: {
        story: 'Real product UI compositions and adjacent components.',
      },
    },
  },
};

export const Tokens: Story = {
  args: {
    scenarioId: 'tokens',
  },
  parameters: {
    docs: {
      description: {
        story: 'Design tokens used by this component.',
      },
    },
  },
};

export const Accessibility: Story = {
  args: {
    scenarioId: 'accessibility',
  },
  parameters: {
    docs: {
      description: {
        story: 'Keyboard, ARIA, labeling, and contrast notes.',
      },
    },
  },
};

export const Playground: Story = {
  args: {
    scenarioId: 'playground',
  },
  parameters: {
    docs: {
      description: {
        story: 'Interactive controls for quick exploration.',
      },
    },
  },
};
