// Generated by scripts/generate-flutter-preview-registry.ts.
// Do not edit by hand.

const supportedPreviewComponents = <String>{
  'alert',
  'badge',
  'button',
  'card',
  'icon-button',
  'spinner',
  'text',
  'text-field',
};
