import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { daisyUiShowcaseEntries } from '../daisyui-showcase.js';
import { mantineShowcaseEntries } from '../mantine-showcase.js';

const repoRoot = process.cwd();
const GENERATED_STORY_MARKER = 'Generated by scripts/generate-showcase-stories.mjs';
const requiredScenarios = [
  'preview',
  'variants',
  'states',
  'composition',
  'tokens',
  'accessibility',
  'playground',
] as const;
const requiredScenarioExports = [
  'Preview',
  'Variants',
  'States',
  'Composition',
  'Tokens',
  'Accessibility',
  'Playground',
] as const;

function storyPath(library: 'mantine' | 'daisyui', id: string) {
  return join(repoRoot, 'stories', library, 'components', `${id}.stories.tsx`);
}

describe('storybook component story structure', () => {
  it('has a committed story generator script', () => {
    const packageJson = JSON.parse(
      readFileSync(join(repoRoot, 'package.json'), 'utf8'),
    );

    expect(existsSync(join(repoRoot, 'scripts/generate-showcase-stories.mjs'))).toBe(
      true,
    );
    expect(packageJson.scripts['generate:stories']).toBe(
      'node scripts/generate-showcase-stories.mjs',
    );
  });

  it('has one Mantine story file per showcase entry', () => {
    const missing = mantineShowcaseEntries
      .map((entry) => storyPath('mantine', entry.id.replace(/^mantine-/, '')))
      .filter((path) => !existsSync(path));

    expect(missing).toEqual([]);
    for (const entry of mantineShowcaseEntries) {
      const file = readFileSync(
        storyPath('mantine', entry.id.replace(/^mantine-/, '')),
        'utf8',
      );
      expect(file).toContain(GENERATED_STORY_MARKER);
    }
  });

  it('has one daisyUI story file per showcase entry', () => {
    const missing = daisyUiShowcaseEntries
      .map((entry) => storyPath('daisyui', entry.id.replace(/^daisyui-/, '')))
      .filter((path) => !existsSync(path));

    expect(missing).toEqual([]);
    for (const entry of daisyUiShowcaseEntries) {
      const file = readFileSync(
        storyPath('daisyui', entry.id.replace(/^daisyui-/, '')),
        'utf8',
      );
      expect(file).toContain(GENERATED_STORY_MARKER);
    }
  });

  it('has scenario controls and variants export in generated component stories', () => {
    for (const [library, entries] of [
      ['mantine', mantineShowcaseEntries],
      ['daisyui', daisyUiShowcaseEntries],
    ] as const) {
      for (const entry of entries) {
        const file = readFileSync(
          storyPath(library, entry.id.replace(new RegExp(`^${library}-`), '')),
          'utf8',
        );

        expect(file).toContain('argTypes');
        expect(file).toContain('scenarioId');
        expect(file).toContain('export const Preview');
        expect(file).toContain('export const Variants');
        expect(file).toContain("scenarioId: 'variants'");
      }
    }
  });

  it('exposes full design-system page scenarios in generated component stories', () => {
    for (const [library, entries] of [
      ['mantine', mantineShowcaseEntries],
      ['daisyui', daisyUiShowcaseEntries],
    ] as const) {
      for (const entry of entries) {
        const file = readFileSync(
          storyPath(library, entry.id.replace(new RegExp(`^${library}-`), '')),
          'utf8',
        );

        for (const scenarioId of requiredScenarios) {
          expect(file).toContain(`scenarioId: '${scenarioId}'`);
          expect(file).toContain(`'${scenarioId}'`);
        }

        for (const exportName of requiredScenarioExports) {
          expect(file).toContain(`export const ${exportName}`);
        }
      }
    }
  });

  it('does not expose the old all-components bucket stories', () => {
    expect(
      existsSync(join(repoRoot, 'stories/mantine/all-components.stories.tsx')),
    ).toBe(false);
    expect(
      existsSync(join(repoRoot, 'stories/daisyui/all-components.stories.tsx')),
    ).toBe(false);
  });

  it('uses fullscreen layout and wide showcase CSS for component stories', () => {
    const previewCss = readFileSync(
      join(repoRoot, 'src/showcase/showcase.css'),
      'utf8',
    );
    const mantineButtonStory = readFileSync(storyPath('mantine', 'button'), 'utf8');
    const daisyButtonStory = readFileSync(storyPath('daisyui', 'button'), 'utf8');

    expect(mantineButtonStory).toContain("layout: 'fullscreen'");
    expect(daisyButtonStory).toContain("layout: 'fullscreen'");
    expect(previewCss).toContain('.tinyrack-showcase-single');
    expect(previewCss).toContain('max-width: 72rem');
    expect(previewCss).toContain('width: min(100%, calc(100vw - 3rem))');
  });

  it('overrides Storybook canvas overflow so long and scrollable previews can scroll', () => {
    const previewCss = readFileSync(join(repoRoot, '.storybook/preview.css'), 'utf8');

    expect(previewCss).toContain('body.sb-show-main');
    expect(previewCss).toContain('overflow: auto');
    expect(previewCss).toContain('#storybook-root');
  });

  it('pins Vitest browser API away from Windows excluded port ranges', () => {
    const vitestConfig = readFileSync(join(repoRoot, 'vitest.config.ts'), 'utf8');

    expect(vitestConfig).toContain('api:');
    expect(vitestConfig).toContain("host: '127.0.0.1'");
    expect(vitestConfig).toContain('port: 61080');
  });
});
