// Generated by scripts/generate-flutter-preview-registry.ts.
// Do not edit by hand.

export const flutterPreviewComponents = [
  'alert',
  'badge',
  'button',
  'card',
  'icon-button',
  'spinner',
  'text',
  'text-field',
] as const;
export type FlutterPreviewComponent = (typeof flutterPreviewComponents)[number];
