name: tinyrack_ui_example
description: Interactive cross-platform previews for tinyrack_ui.
publish_to: none
version: 0.1.0+1

environment:
  sdk: ">=3.12.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.9
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  lucide_flutter: ^1.28.0
  material_ui: ^1.0.0
  tinyrack_ui:
    path: ..
  web: ^1.1.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
