import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import { basename, join, relative, resolve } from 'node:path';

type StorybookIndexEntry = {
  id?: string;
  importPath?: string;
  name?: string;
  title?: string;
  type?: string;
};

type StoryAuditResult = {
  failures: string[];
  file: string;
  id: string;
  library: 'daisyui' | 'mantine';
};

const root = resolve(import.meta.dirname, '..');
const reportPath = resolve(root, 'artifacts/storybook-scenario-audit/audit.json');
const storybookIndexPath = resolve(root, 'storybook-static/index.json');
const componentLibraries = ['mantine', 'daisyui'] as const;
const expectedStoryCounts = {
  daisyui: 58,
  mantine: 95,
} as const;
const forbiddenStorySnippets = [
  'Generated by scripts/generate-showcase-stories.ts',
  'src/showcase',
  'SingleComponentStory',
  'ShowcaseGallery',
  'getShowcase',
  'showcaseEntry',
  'classes(',
  'modifierClass(',
  'selectControlValue(',
  'booleanControlValue(',
  'numberControlValue(',
  'selectDaisyControl(',
] as const;

function storyIdFor(library: 'daisyui' | 'mantine', file: string) {
  return `${library}-${basename(file, '.stories.tsx')}--default`;
}

async function readJson(path: string) {
  return JSON.parse(await readFile(path, 'utf8')) as unknown;
}

function storybookEntries(indexJson: unknown) {
  if (!indexJson || typeof indexJson !== 'object') {
    return [];
  }

  const index = indexJson as { entries?: unknown; stories?: unknown };
  const entries = index.entries ?? index.stories;

  if (!entries || typeof entries !== 'object') {
    return [];
  }

  return Object.values(entries as Record<string, StorybookIndexEntry>);
}

async function readStoryFiles(library: 'daisyui' | 'mantine') {
  const storyDir = resolve(root, 'stories', library, 'components');
  const files = (await readdir(storyDir))
    .filter((file) => file.endsWith('.stories.tsx'))
    .sort();

  return Promise.all(
    files.map(async (file) => ({
      file,
      id: storyIdFor(library, file),
      library,
      source: await readFile(join(storyDir, file), 'utf8'),
    })),
  );
}

function auditStorySource({
  file,
  id,
  library,
  source,
}: Awaited<ReturnType<typeof readStoryFiles>>[number]): StoryAuditResult {
  const failures: string[] = [];

  if (!source.includes('component:')) {
    failures.push('manual story does not declare a component');
  }

  if (!source.includes('export const Default')) {
    failures.push('manual story does not export Default');
  }

  for (const snippet of forbiddenStorySnippets) {
    if (source.includes(snippet)) {
      failures.push(`manual story contains forbidden snippet: ${snippet}`);
    }
  }

  return { failures, file, id, library };
}

function auditStorybookIndex(
  storyFiles: Array<{ id: string; library: 'daisyui' | 'mantine' }>,
  entries: StorybookIndexEntry[],
) {
  const indexedStoryIds = new Set(
    entries
      .filter((entry) => entry.type === undefined || entry.type === 'story')
      .map((entry) => entry.id)
      .filter((id): id is string => typeof id === 'string'),
  );

  return storyFiles
    .filter((story) => !indexedStoryIds.has(story.id))
    .map<StoryAuditResult>((story) => ({
      failures: ['manual story is missing from storybook-static/index.json'],
      file: `${story.id}.stories.tsx`,
      id: story.id,
      library: story.library,
    }));
}

const storyFiles = (
  await Promise.all(componentLibraries.map((library) => readStoryFiles(library)))
).flat();
const indexEntries = storybookEntries(await readJson(storybookIndexPath));
const sourceResults = storyFiles.map(auditStorySource);
const indexResults = auditStorybookIndex(storyFiles, indexEntries);
const countFailures = componentLibraries.flatMap<StoryAuditResult>((library) => {
  const actual = storyFiles.filter((story) => story.library === library).length;
  const expected = expectedStoryCounts[library];

  if (actual === expected) {
    return [];
  }

  return [
    {
      failures: [`expected ${expected} manual stories, found ${actual}`],
      file: `${library}/components`,
      id: `${library}-story-count`,
      library,
    },
  ];
});
const results = [...countFailures, ...sourceResults, ...indexResults];
const failures = results.filter((result) => result.failures.length > 0);

await mkdir(resolve(root, 'artifacts/storybook-scenario-audit'), {
  recursive: true,
});
await writeFile(
  reportPath,
  `${JSON.stringify(
    {
      checkedStories: storyFiles.length,
      failures,
      results,
    },
    null,
    2,
  )}\n`,
);

if (failures.length > 0) {
  throw new Error(
    `Storybook manual story audit failed: ${failures.length} failures. Report: ${relative(
      root,
      reportPath,
    )}`,
  );
}

console.log(
  `Storybook manual story audit passed: ${storyFiles.length} stories checked. Report: ${relative(
    root,
    reportPath,
  )}`,
);
