import { readdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const check = process.argv.includes('--check');
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const componentsRoot = resolve(root, 'packages/ui_flutter/lib/src/components');
const dartOutput = resolve(
  root,
  'packages/ui_flutter/example/lib/preview_registry.g.dart',
);
const typescriptOutput = resolve(
  root,
  'packages/homepage/app/documentation/flutter/preview-registry.generated.ts',
);

const componentFiles = (await readdir(componentsRoot, { recursive: true }))
  .filter((name) => name.endsWith('.dart'))
  .sort();
const components: string[] = [];
for (const file of componentFiles) {
  const source = await readFile(resolve(componentsRoot, file), 'utf8');
  for (const match of source.matchAll(/^\/\/ @tinyrack-preview ([a-z-]+)$/gm)) {
    const component = match[1];
    if (component !== undefined) components.push(component);
  }
}
components.sort();

if (components.length === 0 || new Set(components).size !== components.length) {
  throw new Error('Flutter preview annotations must be present and unique.');
}

const dart = `// Generated by scripts/generate-flutter-preview-registry.ts.
// Do not edit by hand.

const supportedPreviewComponents = <String>{
${components.map((component) => `  '${component}',`).join('\n')}
};
`;
const typescript = `// Generated by scripts/generate-flutter-preview-registry.ts.
// Do not edit by hand.

export const flutterPreviewComponents = [
${components.map((component) => `  '${component}',`).join('\n')}
] as const;
export type FlutterPreviewComponent = (typeof flutterPreviewComponents)[number];
`;

for (const [path, expected] of [
  [dartOutput, dart],
  [typescriptOutput, typescript],
] as const) {
  if (check) {
    const current = await readFile(path, 'utf8').catch(() => '');
    if (current !== expected) {
      throw new Error(`Generated Flutter preview registry is stale: ${path}`);
    }
  } else {
    await writeFile(path, expected);
  }
}
