// Generated by scripts/generate-showcase-stories.mjs
import '../../../src/showcase/showcase.css';
import type { Meta, StoryObj } from '@storybook/react-vite';
import type { ShowcaseScenarioId } from '../../../src/showcase/index.js';
import {
  daisyUiShowcaseEntries,
  SingleShowcaseStory,
} from '../../../src/showcase/index.js';

type ComponentStoryProps = {
  scenarioId?: ShowcaseScenarioId;
};

const entry = daisyUiShowcaseEntries.find(
  (showcaseEntry) => showcaseEntry.id === 'daisyui-menu',
);

if (!entry) {
  throw new Error('Missing showcase entry: daisyui-menu');
}

function MenuStory({ scenarioId = 'preview' }: ComponentStoryProps) {
  return (
    <SingleShowcaseStory entry={entry} library="daisyui" scenarioId={scenarioId} />
  );
}

const meta = {
  title: 'daisyUI/Components/menu',
  component: MenuStory,
  args: {
    scenarioId: 'preview',
  },
  argTypes: {
    scenarioId: {
      control: 'select',
      options: ['preview', 'variants'],
      description:
        'Switch between the default component preview and the variant matrix.',
    },
  },
  parameters: {
    layout: 'fullscreen',
  },
} satisfies Meta<typeof MenuStory>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Preview: Story = {
  args: {
    scenarioId: 'preview',
  },
};

export const Variants: Story = {
  args: {
    scenarioId: 'variants',
  },
};
