import { existsSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';
import packageJson from '../../package.json' with { type: 'json' };

describe('@tinyrack/ui test commands', () => {
  it('checks only Web token outputs during the UI package build', () => {
    expect(packageJson.scripts['build']).toContain(
      'generate-design-tokens.ts --check --web-only',
    );
  });

  it('ships the compliance API and executable from the same package', () => {
    const buildConfig = readFileSync(
      resolve(import.meta.dirname, '../../tsdown.config.ts'),
      'utf8',
    );

    expect(packageJson.bin).toEqual({
      'tinyrack-ui-check': './dist/check/cli.js',
    });
    expect(packageJson.exports['./check']).toEqual({
      '@tinyrack/source': './src/check/index.ts',
      types: './dist/check/index.d.ts',
      import: './dist/check/index.js',
    });
    expect(packageJson.publishConfig.exports['./check']).toEqual({
      types: './dist/check/index.d.ts',
      import: './dist/check/index.js',
    });
    expect(buildConfig).toContain("'check/index': 'src/check/index.ts'");
    expect(buildConfig).toContain("'check/cli': 'src/check/cli.ts'");
  });

  it('keeps generated TypeScript tokens in one flat module', () => {
    const generatedTokens = resolve(import.meta.dirname, 'tokens.ts');
    const legacyTokenDirectory = resolve(import.meta.dirname, 'tokens');

    expect(existsSync(generatedTokens)).toBe(true);
    expect(existsSync(legacyTokenDirectory)).toBe(false);
    expect(readFileSync(generatedTokens, 'utf8')).toContain(
      'Generated by scripts/generate-design-tokens.ts',
    );
  });

  it('publishes its consumer skill without exposing it as a JavaScript subpath', () => {
    const readme = readFileSync(
      resolve(import.meta.dirname, '../../README.md'),
      'utf8',
    );

    expect(packageJson.files).toContain('skills');
    expect(
      existsSync(resolve(import.meta.dirname, '../../skills/tinyrack-ui/SKILL.md')),
    ).toBe(true);
    expect(
      existsSync(
        resolve(import.meta.dirname, '../../skills/tinyrack-ui/agents/openai.yaml'),
      ),
    ).toBe(true);
    expect(
      Object.keys(packageJson.exports).some((path) => path.startsWith('./skills')),
    ).toBe(false);
    expect(
      Object.keys(packageJson.publishConfig.exports).some((path) =>
        path.startsWith('./skills'),
      ),
    ).toBe(false);
    expect(readme).toContain('skills experimental_sync --agent codex --yes');
    expect(readme).not.toContain('skills add ./node_modules');
  });

  it('runs browser coverage directly without a wrapper or fixed API port', () => {
    expect(packageJson.scripts['test:e2e']).toBe(
      'pnpm build && pnpm test:chromium && pnpm test:firefox && pnpm test:webkit:virtual-list',
    );
    expect(packageJson.scripts['test:prepared']).toBe(
      'pnpm test:unit && pnpm test:docs-contract && pnpm test:chromium && pnpm test:firefox && pnpm test:webkit:virtual-list',
    );
    expect(packageJson.scripts['test:docs-contract']).toBe(
      'vitest run --project docs-contract',
    );
    expect(packageJson.scripts['test:chromium']).toBe(
      'vitest run --mode component-coverage --project browser --coverage',
    );
    expect(packageJson.scripts['test:firefox']).toBe(
      'vitest run --mode component-firefox --project browser',
    );
    expect(packageJson.scripts['test:webkit']).toBe(
      'vitest run --mode component-webkit --project browser',
    );
    expect(packageJson.scripts['test:webkit:virtual-list']).toBe(
      'vitest run --mode component-webkit --project browser src/components/virtual-list/virtual-list.browser.test.tsx',
    );

    const vitestConfig = readFileSync(
      resolve(import.meta.dirname, '../../vitest.config.ts'),
      'utf8',
    );
    // The invariant this test is named for is that the browser API binds a
    // free port itself. Asserting the old helper's source text pinned one
    // particular implementation instead, and that implementation reserved a
    // port then released it before Vite rebound it, which is a race.
    expect(vitestConfig).toContain("host: '127.0.0.1'");
    expect(vitestConfig).not.toMatch(/port:\s*\d/);
    expect(vitestConfig).not.toContain('strictPort');
    expect(vitestConfig).not.toContain('retry:');
    expect(vitestConfig).toContain(
      'fileParallelism: !(componentFirefox || componentWebkit)',
    );
    expect(vitestConfig).not.toContain('maxWorkers');
  });

  it('keeps prepared package tests parallel and preserves Firefox failures', () => {
    const rootPackage = JSON.parse(
      readFileSync(resolve(import.meta.dirname, '../../../../package.json'), 'utf8'),
    ) as { scripts: Record<string, string> };
    const ci = readFileSync(
      resolve(import.meta.dirname, '../../../../.github/workflows/ci.yml'),
      'utf8',
    );
    const preparedRunner = readFileSync(
      resolve(import.meta.dirname, '../../../../scripts/run-prepared-tests.ts'),
      'utf8',
    );

    expect(rootPackage.scripts['test']).toBe(
      'pnpm build && node scripts/run-prepared-tests.ts',
    );
    expect(preparedRunner).toContain("'--parallel'");
    expect(preparedRunner).toContain("'--no-bail'");
    expect(preparedRunner).toContain("'test:prepared'");
    expect(preparedRunner).toContain('TINYRACK_UI_TARBALL');
    expect(ci).toContain('id: ui-firefox-test');
    expect(ci).toContain('continue-on-error: true');
    expect(ci).toContain("if: steps.ui-firefox-test.outcome == 'failure'");
    expect(ci).toContain('Preserve the first UI Firefox failure');
    expect(ci).toContain('name: UI Chromium and contracts');
    expect(ci).toContain('name: UI Firefox');
    expect(ci).toContain('name: UI Virtual List WebKit');
    expect(ci).toContain('pnpm --filter @tinyrack/ui test:webkit:virtual-list');
    expect(ci).toContain(`UI_FIREFOX_RESULT: \${{ needs.ui_firefox.result }}`);
    expect(ci).toContain(`UI_WEBKIT_RESULT: \${{ needs.ui_webkit.result }}`);
    expect(ci).not.toContain('playwright install --with-deps');
    expect(ci).toContain('pnpm --filter @tinyrack/docs test:prepared');
    expect(ci).toContain('pnpm --filter @tinyrack/homepage test:prepared');
  });

  it('caches Playwright browsers and the pub cache behind shared actions', () => {
    const repositoryRoot = resolve(import.meta.dirname, '../../../..');
    const ci = readFileSync(
      resolve(repositoryRoot, '.github/workflows/ci.yml'),
      'utf8',
    );
    const playwrightAction = readFileSync(
      resolve(repositoryRoot, '.github/actions/setup-playwright/action.yml'),
      'utf8',
    );
    const flutterAction = readFileSync(
      resolve(repositoryRoot, '.github/actions/setup-flutter/action.yml'),
      'utf8',
    );

    // Browser and SDK setup live in one action each so a cache key or a
    // pinned SDK version cannot drift between the jobs that use them.
    expect(ci).not.toContain('playwright install');
    expect(ci).not.toContain('subosito/flutter-action');
    expect(playwrightAction).not.toContain('playwright install --with-deps');
    expect(playwrightAction).toContain('Install WebKit host dependencies');
    expect(playwrightAction).toContain(
      "runner.os == 'Linux' && contains(inputs.browsers, 'webkit')",
    );
    expect(playwrightAction).toContain('playwright install-deps webkit');
    expect(flutterAction).toContain('path: ~/.pub-cache');

    // The smoke launch has to run on a cache hit too. It is the only thing
    // that catches a restored browser that cannot actually start, and on a
    // hit the install step it used to follow is skipped.
    expect(playwrightAction).toContain('Smoke launch Playwright browsers');
    expect(playwrightAction).not.toMatch(
      /Smoke launch Playwright browsers[\s\S]*?cache-hit/,
    );
  });

  it('keeps CI package-scoped behind one stable gate', () => {
    const repositoryRoot = resolve(import.meta.dirname, '../../../..');
    const ci = readFileSync(
      resolve(repositoryRoot, '.github/workflows/ci.yml'),
      'utf8',
    );
    const publishUi = readFileSync(
      resolve(repositoryRoot, '.github/workflows/publish-npm.yml'),
      'utf8',
    );
    const publishDocs = readFileSync(
      resolve(repositoryRoot, '.github/workflows/publish-docs-npm.yml'),
      'utf8',
    );

    expect(ci).toContain('name: Plan CI changes');
    expect(ci).toContain('node scripts/ci-change-plan.ts');
    expect(ci).toContain('name: CI gate');
    expect(ci).toContain('name: ui-docs-runtime');
    expect(ci).toContain('name: docs-smoke-input');
    expect(ci).toContain('name: flutter-preview-runtime');
    expect(ci.match(/pnpm run tokens:check/g)).toHaveLength(1);
    expect(ci).toMatch(
      /name: Build Homepage Flutter preview[\s\S]*pnpm run tokens:check[\s\S]*name: Homepage package/,
    );
    expect(ci).not.toContain('name: prepared-workspace');
    expect(ci).not.toContain('name: Prepare package outputs');
    expect(ci).toMatch(
      /name: UI Chromium and contracts[\s\S]*name: Build UI package\s+run: pnpm --filter @tinyrack\/ui build/,
    );
    expect(ci).toMatch(
      /name: UI Chromium and contracts[\s\S]*pnpm --filter @tinyrack\/ui test:docs-contract/,
    );
    expect(ci).toContain(
      'tar -xzf "$TINYRACK_UI_TARBALL" -C packages/ui_web --strip-components=1 package/dist',
    );
    expect(ci).toMatch(/name: ui-docs-runtime\s+path: packages/);
    expect(ci).toMatch(
      /name: Homepage package[\s\S]*--filter tinyrack-ui-workspace[\s\S]*--filter @tinyrack\/homepage\.\.\.[\s\S]*name: Check workspace quality/,
    );
    expect(publishUi).toContain(
      'pnpm --filter @tinyrack/ui... install --frozen-lockfile',
    );
    expect(publishDocs).toContain(
      'pnpm --filter @tinyrack/docs... install --frozen-lockfile',
    );
  });
});
