// Generated by scripts/generate-design-tokens.ts. Do not edit.

export const tinyrackBorders = {
  "width": {
    "default": "1px",
    "strong": "2px",
    "accent": "3px"
  },
  "focus": {
    "width": "2px",
    "offset": "2px"
  }
} as const;

export const tinyrackBreakpoints = {
  "xs": "24rem",
  "sm": "40rem",
  "md": "48rem",
  "lg": "64rem",
  "xl": "80rem"
} as const;

export const tinyrackControlMetrics = {
  "sm": {
    "height": "1.75rem",
    "paddingInline": "0.5rem",
    "gap": "0.25rem",
    "fontSize": "xs",
    "lineHeight": "1rem",
    "iconSize": "0.875rem"
  },
  "md": {
    "height": "2rem",
    "paddingInline": "0.75rem",
    "gap": "0.375rem",
    "fontSize": "sm",
    "lineHeight": "1.25rem",
    "iconSize": "1rem"
  },
  "lg": {
    "height": "2.5rem",
    "paddingInline": "1rem",
    "gap": "0.5rem",
    "fontSize": "sm",
    "lineHeight": "1.25rem",
    "iconSize": "1rem"
  }
} as const;

export const tinyrackLayers = {
  "base": 0,
  "chrome": 100,
  "dropdown": 1000,
  "popover": 1100,
  "backdrop": 900,
  "dialog": 1210,
  "toast": 1300,
  "tooltip": 1400
} as const;

export const tinyrackMeasurements = {
  "measure-xs": "4rem",
  "measure-sm": "8rem",
  "measure-md": "12rem",
  "measure-lg": "16rem",
  "measure-xl": "24rem",
  "measure-2xl": "32rem",
  "brand-mark-sm": "4rem",
  "brand-mark-md": "6rem",
  "brand-mark-lg": "8rem",
  "pane-sm": "15rem",
  "pane-md": "18rem",
  "split-pane-min-extent": "12rem",
  "page-width-sm": "64rem",
  "page-width-md": "72rem",
  "page-width-lg": "76rem",
  "page-width-xl": "80rem",
  "reading-width-sm": "44rem",
  "reading-width-md": "48rem",
  "reading-width-lg": "56rem",
  "page-gutter": "clamp(1rem, 4vw, 2.5rem)",
  "control-width-md": "20rem",
  "control-press-distance": "0.0625rem",
  "overlay-width-sm": "20rem",
  "overlay-width-md": "32rem",
  "overlay-width-lg": "48rem",
  "overlay-width-xl": "64rem",
  "overlay-inline-inset": "1.5rem",
  "overlay-closed-scale": "0.98",
  "text-decoration-thickness": "0.08em",
  "text-underline-offset": "0.18em"
} as const;

export const tinyrackMotion = {
  "duration": {
    "fast": "120ms",
    "normal": "160ms",
    "slow": "180ms",
    "number": "600ms",
    "loading": "2.4s"
  },
  "easing": {
    "standard": "ease",
    "easeOut": "ease-out",
    "linear": "linear"
  }
} as const;

export const tinyrackOpacity = {
  "disabled": "0.5",
  "hover": "0.82",
  "backdrop": "0.56"
} as const;

export const tinyrackPalettes = {
  "neutral": {
    "50": "#fafafa",
    "100": "#f5f5f5",
    "200": "#e5e5e5",
    "300": "#d4d4d4",
    "400": "#a3a3a3",
    "500": "#737373",
    "600": "#525252",
    "700": "#404040",
    "800": "#262626",
    "900": "#171717",
    "950": "#0a0a0a"
  },
  "blue": {
    "50": "#eff6ff",
    "100": "#dbeafe",
    "200": "#bfdbfe",
    "300": "#93c5fd",
    "400": "#60a5fa",
    "500": "#3b82f6",
    "600": "#2563eb",
    "700": "#1d4ed8",
    "800": "#1e40af",
    "900": "#1e3a8a",
    "950": "#172554"
  },
  "green": {
    "50": "#f0fdf4",
    "100": "#dcfce7",
    "200": "#bbf7d0",
    "300": "#86efac",
    "400": "#4ade80",
    "500": "#22c55e",
    "600": "#16a34a",
    "700": "#15803d",
    "800": "#166534",
    "900": "#14532d",
    "950": "#052e16"
  },
  "amber": {
    "50": "#fffbeb",
    "100": "#fef3c7",
    "200": "#fde68a",
    "300": "#fcd34d",
    "400": "#fbbf24",
    "500": "#f59e0b",
    "600": "#d97706",
    "700": "#b45309",
    "800": "#92400e",
    "900": "#78350f",
    "950": "#451a03"
  },
  "red": {
    "50": "#fef2f2",
    "100": "#fee2e2",
    "200": "#fecaca",
    "300": "#fca5a5",
    "400": "#f87171",
    "500": "#ef4444",
    "600": "#dc2626",
    "700": "#b91c1c",
    "800": "#991b1b",
    "900": "#7f1d1d",
    "950": "#450a0a"
  }
} as const;

export const tinyrackRadii = {
  "xs": "0.125rem",
  "sm": "0.25rem",
  "md": "0.375rem",
  "lg": "0.5rem",
  "xl": "0.75rem",
  "full": "9999px"
} as const;

export const tinyrackSemanticColors = {
  "light": {
    "surface": "#ffffff",
    "surfaceMuted": "#f5f5f5",
    "surfaceHover": "#eff6ff",
    "surfaceSelected": "#dbeafe",
    "surfacePressed": "#bfdbfe",
    "text": "#171717",
    "textMuted": "#525252",
    "textPlaceholder": "#737373",
    "border": "#737373",
    "borderStrong": "#525252",
    "controlBorder": "#737373",
    "controlTrack": "#737373",
    "focus": "#2563eb",
    "surfaceInverse": "#171717",
    "textInverse": "#fafafa",
    "borderInverse": "#a3a3a3",
    "skeletonFill": "#d4d4d4",
    "skeletonHighlight": "#f5f5f5",
    "primary": "#1d4ed8",
    "primaryHover": "#1e40af",
    "primaryPressed": "#1e3a8a",
    "onPrimary": "#ffffff",
    "info": "#1d4ed8",
    "infoHover": "#1e40af",
    "infoPressed": "#1e3a8a",
    "infoSurface": "#eff6ff",
    "infoSurfaceSubtle": "#eff6ff",
    "infoSurfaceHover": "#dbeafe",
    "infoSurfacePressed": "#bfdbfe",
    "infoBorder": "#2563eb",
    "onInfo": "#ffffff",
    "success": "#15803d",
    "successHover": "#166534",
    "successPressed": "#14532d",
    "successSurface": "#f0fdf4",
    "successSurfaceSubtle": "#f0fdf4",
    "successSurfaceHover": "#dcfce7",
    "successSurfacePressed": "#bbf7d0",
    "successBorder": "#16a34a",
    "onSuccess": "#ffffff",
    "warning": "#92400e",
    "warningHover": "#78350f",
    "warningPressed": "#451a03",
    "warningSurface": "#fffbeb",
    "warningSurfaceSubtle": "#fffbeb",
    "warningSurfaceHover": "#fef3c7",
    "warningSurfacePressed": "#fde68a",
    "warningBorder": "#d97706",
    "onWarning": "#ffffff",
    "danger": "#b91c1c",
    "dangerHover": "#991b1b",
    "dangerPressed": "#7f1d1d",
    "dangerSurface": "#fef2f2",
    "dangerSurfaceSubtle": "#fef2f2",
    "dangerSurfaceHover": "#fee2e2",
    "dangerSurfacePressed": "#fecaca",
    "dangerBorder": "#dc2626",
    "onDanger": "#ffffff",
    "scrim": "#0000008f"
  },
  "dark": {
    "surface": "#0a0a0a",
    "surfaceMuted": "#171717",
    "surfaceHover": "#172554",
    "surfaceSelected": "#1e3a8a",
    "surfacePressed": "#1e40af",
    "text": "#fafafa",
    "textMuted": "#a3a3a3",
    "textPlaceholder": "#a3a3a3",
    "border": "#a3a3a3",
    "borderStrong": "#d4d4d4",
    "controlBorder": "#a3a3a3",
    "controlTrack": "#a3a3a3",
    "focus": "#60a5fa",
    "surfaceInverse": "#fafafa",
    "textInverse": "#171717",
    "borderInverse": "#737373",
    "skeletonFill": "#404040",
    "skeletonHighlight": "#525252",
    "primary": "#60a5fa",
    "primaryHover": "#93c5fd",
    "primaryPressed": "#bfdbfe",
    "onPrimary": "#172554",
    "info": "#93c5fd",
    "infoHover": "#bfdbfe",
    "infoPressed": "#dbeafe",
    "infoSurface": "#172554",
    "infoSurfaceSubtle": "#262d34",
    "infoSurfaceHover": "#1e3a8a",
    "infoSurfacePressed": "#1e40af",
    "infoBorder": "#60a5fa",
    "onInfo": "#172554",
    "success": "#86efac",
    "successHover": "#bbf7d0",
    "successPressed": "#dcfce7",
    "successSurface": "#052e16",
    "successSurfaceSubtle": "#25322a",
    "successSurfaceHover": "#14532d",
    "successSurfacePressed": "#166534",
    "successBorder": "#4ade80",
    "onSuccess": "#052e16",
    "warning": "#fcd34d",
    "warningHover": "#fde68a",
    "warningPressed": "#fef3c7",
    "warningSurface": "#451a03",
    "warningSurfaceSubtle": "#342e1e",
    "warningSurfaceHover": "#78350f",
    "warningSurfacePressed": "#92400e",
    "warningBorder": "#fbbf24",
    "onWarning": "#451a03",
    "danger": "#f87171",
    "dangerHover": "#fca5a5",
    "dangerPressed": "#fecaca",
    "dangerSurface": "#450a0a",
    "dangerSurfaceSubtle": "#332222",
    "dangerSurfaceHover": "#7f1d1d",
    "dangerSurfacePressed": "#991b1b",
    "dangerBorder": "#f87171",
    "onDanger": "#450a0a",
    "scrim": "#000000b8"
  }
} as const;

export const tinyrackShadows = {
  "raised": "0 1rem 2.25rem -1rem rgb(0 0 0 / 0.4)",
  "overlay": "0 1.5rem 3rem -1.25rem rgb(0 0 0 / 0.4)"
} as const;

export const tinyrackSpacing = {
  "3xs": "0.0625rem",
  "xs": "0.25rem",
  "sm": "0.5rem",
  "md": "0.75rem",
  "lg": "1rem",
  "xl": "1.5rem",
  "2xl": "2rem",
  "3xl": "3rem",
  "4xl": "4rem",
  "5xl": "6rem"
} as const;

export const tinyrackSpinnerMetrics = {
  "sizeSm": "0.75rem",
  "sizeMd": "1rem",
  "sizeLg": "1.25rem",
  "strokeWidth": "0.125rem",
  "trackOpacity": "24%"
} as const;

export const tinyrackTypography = {
  "fontStack": {
    "body": "\"IBM Plex Sans\"",
    "heading": "\"IBM Plex Sans\"",
    "mono": "\"IBM Plex Mono\", monospace"
  },
  "fontFamily": {
    "body": "var(--tinyrack-font-body)",
    "heading": "var(--tinyrack-font-heading)",
    "mono": "var(--tinyrack-font-mono)"
  },
  "fontSize": {
    "2xs": "0.6875rem",
    "xs": "0.75rem",
    "sm": "0.875rem",
    "md": "1rem",
    "lg": "1.125rem",
    "xl": "1.25rem",
    "2xl": "1.5rem",
    "3xl": "1.875rem",
    "4xl": "2.25rem",
    "5xl": "2.75rem",
    "6xl": "3.5rem"
  },
  "lineHeight": {
    "xs": "1",
    "sm": "1.2",
    "md": "1.5",
    "lg": "1.65",
    "xl": "1.75"
  },
  "letterSpacing": {
    "none": "0",
    "sm": "0.02em",
    "md": "0.06em",
    "lg": "0.08em",
    "xl": "0.12em"
  },
  "fontWeight": {
    "regular": 400,
    "medium": 600,
    "heading": 650,
    "bold": 700,
    "strong": 700
  },
  "textStyle": {
    "caption": {
      "fontSize": "xs",
      "lineHeight": "sm",
      "letterSpacing": "none",
      "fontWeight": "regular"
    },
    "label": {
      "fontSize": "xs",
      "lineHeight": "xs",
      "letterSpacing": "lg",
      "fontWeight": "strong"
    },
    "body": {
      "fontSize": "md",
      "lineHeight": "md",
      "letterSpacing": "none",
      "fontWeight": "regular"
    },
    "bodySm": {
      "fontSize": "sm",
      "lineHeight": "md",
      "letterSpacing": "none",
      "fontWeight": "regular"
    },
    "code": {
      "fontSize": "sm",
      "lineHeight": "lg",
      "letterSpacing": "none",
      "fontWeight": "regular"
    },
    "headingSm": {
      "fontSize": "lg",
      "lineHeight": "sm",
      "letterSpacing": "none",
      "fontWeight": "heading"
    },
    "headingMd": {
      "fontSize": "2xl",
      "lineHeight": "sm",
      "letterSpacing": "none",
      "fontWeight": "heading"
    },
    "headingLg": {
      "fontSize": "3xl",
      "lineHeight": "sm",
      "letterSpacing": "none",
      "fontWeight": "heading"
    },
    "display": {
      "fontSize": "5xl",
      "lineHeight": "sm",
      "letterSpacing": "none",
      "fontWeight": "heading"
    },
    "displayLg": {
      "fontSize": "6xl",
      "lineHeight": "xs",
      "letterSpacing": "none",
      "fontWeight": "heading"
    }
  }
} as const;

export type TRControlUiSize = keyof typeof tinyrackControlMetrics;
